### ISSUE TITLE
Name Missing

### ISSUE THREAD

**Issue by AwazS** [zilindeng/ysdn.info#15]
Hi. My name is missing from the list of 2014 graduates. My name is Awazadeen Abdul Samad. I went by Awaz Samad

**Comment by Shrinks99** [comment]
Hi Awaz!  Thanks for making an issue!  I'll update this right now!

Would you happen to have a lead on any of the 2014 site files or any grad show assets / ephemera we could put up on here?

**Comment by Shrinks99** [comment]
Fixed in 9b64914bb5aa4b070a0b82991a33323c5b421d3d

**Comment by AwazS** [comment]
Hi, I may have the files. I helped on the grad site but I’ll have to go
through some old hard drives. Once I do I’ll let you know.

Thanks for adding me to the page!

-Awaz

**Comment by Shrinks99** [comment]
Amazing!! WARCIT hasn't been updated to handle offline sites to the level that I'd like, so it may take a bit for me to get online here, but knowing the files might exist and having a copy of them is a big step forward.

Please do take a look! :)
